apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: springboot
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000